Repository jenkinsci/pipeline-stage-view-plugin, pull requests merged in 2020-09, with the labels that each got.

#100 [JENKINS-63516] Do not test password parameters with the input step
  rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/InputStepTest.java
  rest-api/src/test/resources/com/cloudbees/workflow/rest/endpoints/sample-flow.groovy
Labels: internal

#104 JENKINS-63556 Fix contrast issues
  ui/src/main/js/view/templates/stage-logs.less
  ui/src/main/js/view/widgets/dialog/style.less
Labels: bug

#105 Fix plugin site GitHub link
  rest-api/pom.xml
  ui/pom.xml
Labels: maintenance

#107 Remove JS calculation of width, just use css.
  ui/src/main/js/view/stage-logs.js
  ui/src/main/js/view/widgets/dialog/index.js
  ui/src/main/less/stageview_adjunct.less
Labels: enhancement

#109 Fixup chinese translation
  ui/src/main/resources/com/cloudbees/workflow/ui/view/Message_zh_CN.properties
Labels: maintenance
