Repository jenkinsci/pipeline-stage-view-plugin, pull requests merged in 2020-11, with the labels that each got.

#127 Fixing README.md to fix changelog
  README.md
Labels: documentation

#126 Upgrade jquery to 3.5.1
  .gitignore
  pom.xml
  ui/gulpfile.js
  ui/jest.config.json
  ui/package-lock.json
  ui/package.json
  ui/pom.xml
  ui/src/main/js/jQuery/index.js
  ui/src/main/js/mvc/index.js
  ui/src/main/js/stageview.js
  ui/src/main/js/util/isTestEnv.js
  ui/src/main/js/view/pipeline-staged.js
  ui/src/main/js/view/stage-logs.js
  ui/src/main/js/view/templates/pipeline-staged.hbs
  ui/src/main/js/view/widgets/popover/index.js
  ui/src/test/js/README.md
  ui/src/test/js/helper.js
  ui/src/test/js/jQuery/index.spec.js
  ui/src/test/js/model/job-history-listener.spec.js
  ui/src/test/js/model/run-changesets.spec.js
  ui/src/test/js/model/runs-stage-grouped.spec.js
  ui/src/test/js/util/formatters.spec.js
  ui/src/test/js/util/timeout-spec.js
  ui/src/test/js/util/timeout.spec.js
  ui/src/test/js/util/url.spec.js
  ui/src/test/js/view/info-action-popover.spec.js
  ui/src/test/js/view/pipeline-staged.spec.js
  ui/src/test/js/view/run-changesets.spec.js
  ui/src/test/js/view/run-input-required.spec.js
  ui/src/test/js/view/stage-logs-spec.js
Labels: dependencies, maintenance

#122 JENKINS-64015 Fix Job urls are set to the same color as the background in the Pipeline logs
  ui/src/main/js/view/widgets/dialog/style.less
Labels: bug

#120 Keep input popovers open for longer
  ui/src/main/js/view/run-input-required.js
  ui/src/main/js/view/widgets/popover/index.js
Labels: bug
