Repository jenkinsci/pipeline-stage-view-plugin, pull requests merged in 2023-01, with the labels that each got.

#257 remove momentjs
  ui/pom.xml
  ui/src/main/js/view/templates/index.js
Labels: removed

#263 fix bom artifact, align with core version
  pom.xml
Labels: dependencies

#264 Stop testing non-block-scoped `stage`
  rest-api/src/test/java/com/cloudbees/workflow/flownode/CachingTest.java
  rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/FlowNodeAPITest.java
  rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/InputStepTest.java
  rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/JobAndRunAPITest.java
  rest-api/src/test/java/com/cloudbees/workflow/rest/endpoints/ParallelStepTest.java
  rest-api/src/test/resources/com/cloudbees/workflow/rest/endpoints/sample-flow.groovy
Labels: developer
