Repository jenkinsci/pipeline-stage-view-plugin, pull requests merged in 2024-08, with the labels that each got.

#337 Enable NPM updates
  .github/dependabot.yml
Labels: chore

#341 parcel update
  .github/CODEOWNERS
  Jenkinsfile
  ui/package-lock.json
  ui/package.json
Labels: dependencies

#334 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#344 Cap `runCount` in unused `JobApi.doDescribe`
  rest-api/src/main/java/com/cloudbees/workflow/rest/external/JobExt.java
Labels: bug
