Repository jenkinsci/pipeline-stage-view-plugin, pull requests merged in 2025-02, with the labels that each got.

#361 [JENKINS-75043] Add LICENSE file
  LICENSE
Labels: documentation

#360 Migrate from EE 8 to EE 9 (fully)
  pom.xml
  rest-api/src/main/java/com/cloudbees/workflow/rest/endpoints/RunAPI.java
Labels: internal

#365 Revert "Fix pipeline box overflow with scroll"
  ui/src/main/js/view/templates/pipeline-staged.less
  ui/src/main/less/stageview.less
Labels: bug

#364 Fix average times markup
  ui/src/main/js/view/templates/pipeline-staged.hbs
  ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html
  ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html
  ui/src/test/resources/view/pipeline_staged/render/expected.html
Labels: bug

#366 Fix release-drafter.yml configuration
  .github/release-drafter.yml
Labels: developer

#369 Add the missing forward slash to run relative url
  ui/src/main/js/view/templates/pipeline-staged.hbs
  ui/src/test/resources/view/pipeline_staged/render/03_rest_api_runs_checkpoint_rerun.html
  ui/src/test/resources/view/pipeline_staged/render/04_rest_api_runs_failed.html
  ui/src/test/resources/view/pipeline_staged/render/07_rest_api_runs_in_progress.html
  ui/src/test/resources/view/pipeline_staged/render/08_rest_api_unstable_run.html
Labels: bug
